[project]
name = "qoslab-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "harrylaulau", email = "dev+github@harrylaulau.me" }]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "numpy>=2.2.3",
 "websockets>=15.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/qoslab-py"]
