[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "pyvisa>=1.14.1",
    "websockets>=15.0",
    "qoslabpy",
]

[dependency-groups]
dev = ["fastapi[standard]>=0.115.8"]

[tool.uv.sources]
qoslabpy = { path = "../qoslabpy", editable = true }

[tool.uv]
link-mode = "copy"
