[project]
name = "qoslab-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
 "qoslab-lib",
]

[dependency-groups]
dev = ["fastapi[standard]>=0.115.8"]

[tool.uv.sources]
qoslab-lib = { path = "../qoslab-lib", editable = true }

[tool.uv]
link-mode = "copy"
