[project]
name = "qoslabapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.115.8",
    "h5py>=3.13.0",
    "pandas>=2.2.3",
    "qoslablib",
]

[dependency-groups]
dev = ["fastapi[standard]>=0.115.8"]

[tool.uv.sources]
qoslablib = { path = "../qoslablib", editable = true }

[tool.uv]
link-mode = "copy"
